config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :shits do 
    resources :comments, only: [:create, :destroy]
    resource :like, only: [:create, :destroy], module: :shits
  end

  root 'shits#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shit
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/shit.rb
class Shit < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes, :as => :likeable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :shits
  has_many :comments
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = current_user.comments.build(comment_params)
    @shit = Shit.find(params[:shit_id])
    @comment.shit = @shit
    if @comment.save
      flash[:success] = "Comment submitted!"
      redirect_to @shit
    else
      flash[:warning] = "There was a problem submitting your comment"
      redirect_to @shit
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/shits/likes_controller.rb
class Shits::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_shit

  def create
    @shit.likes.where(user_id: current_user.id).first_or_create
    flash[:success] = "You liked this!"
    redirect_to @shit
  end

  private
    def get_shit
      @shit = Shit.find(params[:shit_id])
    end
end

app/controllers/shits_controller.rb
class ShitsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :get_shit, only: [:show, :edit, :update, :destroy]

  def index
    @shits = Shit.last(10).reverse
  end

  def show

  end

  def new
    @shit = Shit.new
  end

  def create
    @shit = current_user.shits.build(shit_params)
    if @shit.save
      flash[:success] = "Dumb Shit Submitted!"
      redirect_to @shit
    else
      render 'new'
    end
  end

  def edit
    if current_user != @shit.user
      flash[:warning] = "You are not authorized to do that!"
      redirect_to root_path
    end
  end

  def update
    if current_user != @shit.user
      flash[:warning] = "YOu are not authorized to do that!"
      redirect_to root_path
    end
    if @shit.update_attributes(shit_params)
      flash[:success] = "Shit updated!"
      redirect_to @shit
    else
      render 'edit'
    end
  end

  private
    def get_shit
      @shit = Shit.find(params[:id])
    end

    def shit_params
      params.require(:shit).permit(:title, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="row comment-form">
  <div class="col-md-6 col-md-offset-1">
    <% if !user_signed_in? %>
      <%= link_to 'Login', new_user_session_path %> 
      to like or comment
    <% else %>
      <%= form_for([@shit, Comment.new], :html => {:class => 'form-horizontal'}) do |f| %>
        <div class="form-group">
	  <%= f.text_area :body, class: 'form-control', rows: '3', placeholder: 'Comment' %>
	</div>

	<div class="form-group">
	  <%= f.submit 'Submit', class: 'btn btn-default' %>
	</div>
      <% end %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <h3>Latest Comments</h3>
    <% if @shit.comments.any? %>
      <% @shit.comments.reverse.each do |comment| %>
        <div class="panel panel-default">
	  <div class="panel-body">
	    <%= comment.body %>
	  </div>
	  <div class="panel-footer">
	    <small>
	      <%= comment.user.username || comment.user.email %> - 
	      <%= time_ago_in_words comment.created_at %>
	    </small>
	  </div>
	</div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_adsense.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- dumbstuffpeopledo -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9292388460078962"
     data-ad-slot="5232951901"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-98342094-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-flud">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#dumb-navbar" aria-expanded="false">
	<span class="sr-only">Toggle Navigation</span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">DSPD</a>
    </div>

    <div class="collapse navbar-collapse" id="dumb-navbar">
      

      <ul class="nav navbar-nav navbar-right">
	<% if user_signed_in? %>
	  <li class="dropdown">
	    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
	      <%= current_user.username || current_user.email %> <span class="caret"></span>
	    </a>
	    <ul class="dropdown-menu">
	      <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
	      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
	    </ul>
	  </li>
	<% else %>
	  <li><%= link_to 'Sign In', new_user_session_path %></li>
	  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
	<% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dumb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
	  <%= message %>
	</div>
      <% end %>
      <%= yield %>

      <%= render 'layouts/analytics' %>
    </div>
  </body>
</html>

app/views/shits/_form.html.erb
<%= form_for(@shit, :html => {:class => 'form-horizontal'}) do |f| %>
  <div class="form-group">
    <%= f.label :title, class: 'col-md-2 control-label' %>
    <div class="col-md-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'col-md-2 control-label' %>
    <div class="col-md-10">
      <%= f.text_area :description, class: 'form-control', rows: '3' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-10 col-md-offset-2">
      <%= f.submit 'Create', class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/shits/_shit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <a href="<%= shit_path(shit) %>">
      <h3 class="panel-title">
	<%= shit.title %>
      </h3>
    </a>
  </div>
  <div class="panel-body">
    <%= simple_format shit.description %>
  </div>
  <div class="panel-footer">
    <small>
      <%= shit.user.username || shit.user.email %> - 
      <%= time_ago_in_words(shit.created_at) %> ago
    </small>
  </div>
</div>

app/views/shits/edit.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Edit Shit</h1>
    <%= render 'form' %>
  </div>
  <div class="col-md-4">
    <div class="ad-div">
      <%= render 'layouts/adsense' %>
    </div>
    <%= render 'layouts/adsense' %>
  </div>
</div>

app/views/shits/index.html.erb
<div class="row">
  <div class="col-md-8">
    <% if user_signed_in? %>
      <div class="pull-right new-button">
	<%= link_to 'Create New', new_shit_path, class: 'btn btn-success' %>
      </div>
    <% end %>
    <h1>The Dumb Shit</h1>
    <% if @shits.any? %>
      <%= render @shits %>
    <% end %>
  </div>
  <div class="col-md-4">
    <div class="ad-div">
      <%= render 'layouts/adsense' %>
    </div>
    <%= render 'layouts/adsense' %>
  </div>
</div>

app/views/shits/new.html.erb
<div class="new">
  <div class="col-md-8">
    <h1>New Shit</h1>
    <%= render 'form' %>
  </div>
  <div class="col-md-4">
    <div class="ad-div">
      <%= render 'layouts/adsense' %>
    </div>
    <%= render 'layouts/adsense' %>
  </div>
</div>

app/views/shits/show.html.erb
<div class="row">
  <div class="col-md-8">
    <% if user_signed_in? && current_user == @shit.user %>
      <div class="pull-right new-button">
	<%= link_to 'Edit', edit_shit_path(@shit), class: 'btn btn-primary' %>
      </div>
    <% end %>
    <h1><%= @shit.title %></h1>
    <div class="panel panel-default">
      <div class="panel-body">
	<%= simple_format @shit.description %>
      </div>
      <div class="panel-footer clearfix">
	<small>
	  <%= @shit.user.username || @shit.user.email %> - 
	  <%= time_ago_in_words(@shit.created_at) %>
	</small>
	<div class="pull-right">	  
	  <%= form_for([@shit, Like.new], :url => shit_like_path(@shit), :html => {:class => 'form-inline'}) do |f| %>
	    <button type="submit" class="btn btn-sm btn-default">
	      <span class="glyphicon glyphicon-heart"></span>	  
	      <span class="badge">
		<%= @shit.likes.count %>
	      </span>
	    </button>
	  <% end %>	  
	</div>
      </div>
    </div>
    <%= link_to 'Back to List', shits_path %>
  </div>
  <div class="col-md-4">
    <div class="ad-div">
      <%= render 'layouts/adsense' %>
    </div>
    <%= render 'layouts/adsense' %>
  </div>
</div>
<%= render 'comments/form' %>